# Generated by Django 3.2.4 on 2021-06-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150)),
                ('identifier', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images/%y/%m')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/%y/%m')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/%y/%m')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/%y/%m')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='generators.generator')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('placeholder', models.CharField(max_length=100)),
                ('input_name', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('TextField', 'text'), ('EmailField', 'mail'), ('FileField', 'file')], max_length=30)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='generators.step')),
            ],
        ),
    ]
