# Generated by Django 3.2.4 on 2021-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='require',
            field=models.BooleanField(default=True),
        ),
    ]
