# Generated by Django 3.2.4 on 2021-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0002_field_require'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
