# Generated by Django 3.2.4 on 2021-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0004_alter_field_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.CharField(choices=[('text', 'text'), ('email', 'email'), ('file', 'file')], max_length=30),
        ),
    ]
