# Generated by Django 3.2.4 on 2021-06-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0005_auto_20210627_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='data',
        ),
    ]
